services:
  - type: worker
    name: deepseek-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: AUTH_TOKEN
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: PORT
        value: "8000"
